[build]
  command = "npm run build:client"
  publish = "dist"

[[redirects]]
  # This will be updated once your Railway backend is live
  from = "/api/*"
  to = ":BACKEND_URL/api/:https://truecost-backend-czfm.onrender.com"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
